### ISSUE TITLE
Document *all* variables available in rules.

### ISSUE THREAD

**Issue by madorb** [auth0/rules#108]
Is there any complete documentation about the variables available within rules? I can find no reference in documentation to the `auth0` object, but yet it's used here

https://github.com/auth0/rules/blob/2392ea11601ec0b220e4b3c3a2408cd3a1f50233/redirect-rules/simple/rule.js

as `auth0.baseUrl`.  (this is very helpful for instance, if i need to do a client-credentials grant against the current auth0 account without hardcoding)

As a user - having undocumented variables in examples is incredibly confusing. i'd love to see the documentation updated to include *all* the variables that are available within a rule (including global).

**Comment by madorb** [comment]
Ah, digging through the forum finally got me this:  https://auth0.com/forum/t/what-is-the-auth0-variable-that-appear-in-the-rules/3755

"Its a global instance of Auth0's javascript sdk at 2.0.0-alpha5" - with no further information. Are they referring to this: https://auth0.com/docs/libraries/auth0js ?? it doesn't appear to be...

**Comment by AmaanC** [comment]
Good points, thanks!
When Abhishek said that on the forum, he meant version `2.0.0-alpha5` of our node-auth0 package here:
https://github.com/auth0/node-auth0.

Regarding other global variables that might be available in Rules, I've filed a request with the docs team here:
https://github.com/auth0/docs/issues/3936

**Comment by shawnmclean** [comment]
This section of the docs contains references to the available modules and what you may be able to require: https://auth0.com/docs/rules/current#available-modules

**Comment by villeodell** [comment]
Was this misunderstood when closed?  It was not about available modules that can be required but rather a desire to have documentation regarding all objects/variables that are available to rules by default, e.g. auth0, user, context, others(?).

_Basically, to have this for all objects/variables available within rules --> https://auth0.com/docs/rules/current/context_

Information about the user object is spread out in multiple places..

There is some documentation of the auth0 object here: https://auth0.com/docs/rules/current/management-api

In case anyone is arriving here looking for that (as I did) sticking this code in a rule to inspect the objects you are interested in may be a help:

`const objects = [auth0, user, context];
  objects.forEach((obj) => console.dir(obj, { depth: 4 }));`

**Comment by shawnmclean** [comment]
Hey @villeodell, on the rules docs (https://auth0.com/docs/rules/current#rule-syntax), there is a list of arguments passed in, which contains information about the user object (https://auth0.com/docs/user-profile/user-profile-structure). Is this documentation lacking? Also, if possible, could you point me to the other docs for the user object?

When you scroll down, there is a title about more available modules that points to this page https://auth0.com/docs/appliance/modules. That contains lists of modules such as `auth0`.
