### ISSUE TITLE
redirect-rules/simple - Still valid? 

### ISSUE THREAD

**Issue by joshRpowell** [auth0/rules#126]
I'm following all the steps here: 
https://github.com/auth0/rules/tree/master/redirect-rules/simple

Using the following URL:
```
https://DOMAIN.auth0.com/authorize?response_type=token&scope=openid%20profile&client_id=CLIENT_ID&redirect_uri=http://jwt.io&connection=Username-Password-Authentication
```

I'm redirected to
```
https://nasbnation.auth0.com/login/callback?state=S7dScBNwLS1HVt_D9DqIQ5NIXtOlBtQ8
```

I get the following response:
```
Invalid redirect URL https://wt-peter-auth0_com-0.run.webtask.io/simple-redirect-rule-consent-form';var CONSENT_FORM_URL = 'https://wt-peter-auth0_com-0.run.webtask.io/simple-redirect-rule-consent-form?auth0_domain=nasbnation.auth0.com
```

My real-time Webtask Logs return: 
```
9:36:59 PM: new webtask request 1507167419882.564674
9:36:59 PM: finished webtask request 1507167419882.564674 with HTTP 200 in 107ms
```

Am I missing something?  Perhaps the library has changed?

**Comment by jmangelo** [comment]
This seems to be related to an incorrectly configured `CONSENT_FORM_URL` configuration variable as the error response shows the invalid redirect URL with a bit more content than what it would be expected.

Also replied through: https://community.auth0.com/questions/9704/redirect-rulessimple-example-still-valid
