### ISSUE TITLE
Linking accounts takes all user details from the primaryUser and overrides all modified attributes of the current user

### ISSUE THREAD

**Issue by ethanyoung** [auth0/rules#137]
One of my rule added some extra attributes to the `user`, like `given_name` and `family_name`, and I can see these attributes returned from Auth0 after the authentication.

However, If I added a rule for linking accounts before the existing rule, and set up the `primaryUser` attribute in `context`, even though the next rule still adds the extra attributes, the payload returned by Auth0 only contains those owned by the primary user stored on Auth0.

Is this an expected behaviour? Or did I missed something?

Thanks.

**Comment by joshcanhelp** [comment]
Very delayed response here but for anyone else having this issue ... data added  to the `user` object is only available in the Rule pipeline (i.e. any Rule running after the one adding the data). If you want that data available in the ID token returned to an application or on the `/userinfo` endpoint, you'll need to add a custom claim:

https://auth0.com/docs/tokens/json-web-tokens/json-web-token-claims#custom-claims
