### ISSUE TITLE
redirect-rules/simple - error: unable to resolve jtn to webtask token

### ISSUE THREAD

**Issue by guillaumecodet** [auth0/rules#168]
I'm trying the example, and I get this error after the first redirection:

unable to resolve jtn to webtask token

Can someone help me please ?

Thank you.

**Comment by jmn8718** [comment]
I get the same error, but if you create a webtask:
`wt create https://raw.githubusercontent.com/auth0/rules/master/redirect-rules/simple/webtask.js -n form` then the example works
