### ISSUE TITLE
How to write unit tests for Auth0 rules

### ISSUE THREAD

**Issue by junaidahmed92** [auth0/rules#189]
I have multiple rules in my tenant and now I want to write unit tests for my rules. Now the issue is in the docs (https://auth0.com/docs/support/testing) it’s written that we can use https://www.npmjs.com/package/auth0-rules-testharness module for unit test our rules but I think the explanation is old and it’s not updated because in the sample project (https://github.com/tawawa/auth0-rules-testharness-sample) we need to add webtask token and sandbox url and now we can’t find webtask token in Auth0 dashboard (https://manage.auth0.com/#/account/webtasks) and also where can I get this sandbox url? Any help?

**Comment by yperevoznikov** [comment]
You may use version control to keep source of your rules - https://auth0.com/docs/extensions/github-deploy . Now, you have code on your disc to test, for example like this:

Rule file `my-rule.js`:
```
function myRule(user, context, callback) {
	callback(null, user, context);
}
```

And test file:
```
describe('My rule', () => {

  eval(fs.readFileSync('./my-rule.js', 'utf8'));

  it('should successfully determine Okta', (done) => {
    myRule({}, {}, cb);
    function cb(err, user, ctx) {
      // Check logic here...
    }
  });

});
```

**Comment by Maxim-Filimonov** [comment]
Is this still valid? I don't believe it's possible to use named function ? Doesn't auth0 requires function to be unnamed?

**Comment by joshcanhelp** [comment]
We also have unit tests in this repository that you're able to copy and use:

https://github.com/auth0/rules/tree/master/test/rules
