### ISSUE TITLE
Can I Require?

### ISSUE THREAD

**Issue by sdrioux** [auth0/rules#203]
Not sure if this is the correct place for this, but your `canirequire` page is broken, due to a problem with JQuery.

On page load it receives this error:

```
auth0-extensions.github.io/:48 GET https://code.jquery.com/jquery-3.3.1.min.js net::ERR_SSL_VERSION_INTERFERENCE
```

**Comment by fyockm** [comment]
@sdrioux i do not receive the same error from https://auth0-extensions.github.io/canirequire/

what os and browser are you using? do you have antivirus or some other blocker that might be getting in the way?

**Comment by sdrioux** [comment]
mac v10.14.3, Chrome v.73.0.3683.103.  No antivirus.

**Comment by joshcanhelp** [comment]
Closing for now, let us know if there is still a problem here.
