### ISSUE TITLE
Adding another query param when setting context.redirect.url

### ISSUE THREAD

**Issue by mcblum** [auth0/rules#211]
I'd like to redirect users after they register to our service and pass the state and a JWT we created in the rule that contains things like their user id, email, etc... Essentially the problem we're trying to solve is that we want to kick off a bunch of tasks when a new user registers.

When I add a `?token=${token}` state is not passed anymore, so it appears I can't pass both in. There are no docs for how rules work under the hood as far as I can tell, so it appears it just doesn't work.

Is there a better way to do this? Am I missing something?

Thanks,
Matt

**Comment by joshcanhelp** [comment]
I tested this and was able to add additional query parameters on the redirect out. I did not dig into why it works now and not before but I think we can consider this fixed 👍
