### ISSUE TITLE
Where does the auth0 object come from?

### ISSUE THREAD

**Issue by tommedema** [auth0/rules#217]
### Description

Lots of scripts are referencing a magic `auth0` global object, e.g. at https://github.com/auth0/rules/blob/master/src/rules/roles-creation.js#L33

Where does this come from and where is it documented? Can this be used to receive access tokens to authenticate with the management API?

**Comment by joshcanhelp** [comment]
Apologies for the long delay in responding ... that global is documented here:

https://auth0.com/docs/best-practices/rules-best-practices/rules-environment-best-practices#auth0-object
