### ISSUE TITLE
Pull rules from existing repositories

### ISSUE THREAD

**Issue by ryan-cahill** [auth0/rules#223]
### Describe the problem you'd like to have solved

As it stands, rules are scripts that live only on auth0 and are saved and tested there. once a rule is overwritten, there's no good way to view changes or revert to old versions.

### Describe the ideal solution

It would be really helpful if it was possible to tie each rule to a git repo and a filename inside of it. In doing so, the user would be able to save and edit versions safely without being too concerned about breaking something in the auth0 editor and not being able to revert changes. In setting this repo, auth0 would pull the code specified at the repo url (on a specified branch?) for the rule rather than using what was provided in the editor.

## Alternatives and current work-arounds

Our current workaround is to save all of our rule scripts in a separate repo, then copy/paste each rule to the auth0 editor when we're done editing.

**Comment by seejee** [comment]
Hi @ryan-cahill! 

Auth0 has a few different options for syncing Rules code with a git repo:

We have the [Auth0 Deploy CLI](https://auth0.com/docs/extensions/deploy-cli) that will synchronize nearly all aspects of your auth0 configuration (including Rules) to a file or directory. You can incorporate this into your CI/CD pipeline to push changes to auth0 automatically.

We also have extensions for several source control platforms (e.g. [Github](https://auth0.com/docs/extensions/github-deploy)) to automatically synchronize changes to auth0 as well.

Please take a look at these, and if they don't meet your needs, we'd love to hear why!

**Comment by ryan-cahill** [comment]
Thank you! I was unaware that auth0 had extensions
