### ISSUE TITLE
Context.Authentication possibly undefinded

### ISSUE THREAD

**Issue by mattcosta7** [auth0/rules#267]
https://github.com/auth0/rules/blob/dc917b5d7cce9256243abbeffd2f4725b502c4c1/src/rules/require-mfa-once-per-session.js#L14

In the last few days, with no other changes to our auth0 config, we noticed that in this rule, context.authentication is sometimes undefined, causing an error to throw on this rule, unauthenticating our users temporarily.  Should there be a scenario where this is possible?

**Comment by mattcosta7** [comment]
In chatting on a ticket with auth0 support, it seems like context.authentication is currently undefined when using refresh tokens, so a rule like this will fail in that case

**Comment by joshcanhelp** [comment]
@mattcosta7 Appreciate the report here and apologies for the long delay in getting this fix in place!
