### ISSUE TITLE
link-users-by-email

### ISSUE THREAD

**Issue by doapp-ryanp** [auth0/rules#54]
In https://github.com/auth0/rules/blob/master/rules/link-users-by-email.md where is `userApiUrl` defined? Should the the built in `auth0.baseUrl` be used instead?

**Comment by revett** [comment]
+1

**Comment by revett** [comment]
@doapp-ryanp 

The line needs to be changed to:

```js
url: auth0.baseUrl + '/users/' + user.user_id + '/identities',
```

**Comment by doapp-ryanp** [comment]
Yup - I have this outstanding PR that fixes this and other issues https://github.com/auth0/rules/pull/56
