### ISSUE TITLE
Rules not applied when impersonating user

### ISSUE THREAD

**Issue by sjkp** [auth0/rules#57]
Is it correct that rules are not applied when I logon as another user, by using the impersonation feature. 

If so, then how are we supposed to be able to use rules to their full potential. I add extra claims during login, those are missing when I'm impersonating the user.

**Comment by sandrinodimattia** [comment]
Rules run for every authentication transaction, including impersonation. Have you tried a simple `console.log` in a rule and then use `wt logs` to see what happens?

**Comment by sjkp** [comment]
The rules do get applied I must admit, but in my app, i have changed the scope to  scope: 'openid app_metadata' so my jwt token contains the app_metadata, is there any way to do the same with the impersonate functionality.

**Comment by sandrinodimattia** [comment]
Yes, but you'll need to call the API yourself instead of using the API explorer or the dashboard.

https://auth0.com/docs/auth-api#!#post--users--user_id--impersonate

**Comment by sjkp** [comment]
@sandrinodimattia  thanks - that works! not as easy as hoped for, now I have to build a UI for the support people - but better than implementing it myself.

**Comment by eyn** [comment]
Would be great if the impersonation UI in the dashboard was extended to allow us to specify scope for impersonation. Just hit this too.

**Comment by jordanh** [comment]
+1 to @eyn, allowing the specification of scope would be hugely helpful!
