### ISSUE TITLE
Using context.stats.loginsCount to detect signups

### ISSUE THREAD

**Issue by thameera** [auth0/rules#64]
We can detect a new signup by checking if `context.stats.loginsCount` is equal to 1 ([example](https://github.com/auth0/rules/blob/master/rules/slack.md)).

Why are we setting a new variable in `app_metadata` in the following rule? https://github.com/auth0/rules/blob/master/rules/signup.md

Is this for a rule execution stage when the `context.stats` might not be available such as `pre_authorize` or `user_registration`?

**Comment by david3310** [comment]
I fixed something on your example . Now it works well in my side
It's my rule code:

function(user, context, callback) {
   user.app_metadata = user.app_metadata || {};
  // short-circuit if the user signed up already
  if (context.stats.loginsCount > 1) {
    user.app_metadata.just_signedUp = false;
  } else {
    user.app_metadata.just_signedUp = true;
  }

 auth0.users.updateAppMetadata(user.user_id, user.app_metadata)
    .then(function(){
      callback(null, user, context);
    })
    .catch(function(err){
      callback(err);
    });

  callback(null, user, context);
}

**Comment by shawnmclean** [comment]
Thanks for the response @talent3310.
