### ISSUE TITLE
userApiUrl is undefined - line 31

### ISSUE THREAD

**Issue by sbefort** [auth0/rules#67]
https://github.com/auth0/rules/blob/master/rules/link-users-by-email.md

What should the value of userApiUrl be?

**Comment by seanmangar** [comment]
+1 getting the same error

**Comment by sgtpepper43** [comment]
![image](https://cloud.githubusercontent.com/assets/2449014/17825988/b615d780-6629-11e6-858f-1de308e71ef9.png)

**Comment by kuljaninemir** [comment]
Getting this error as well.

**Comment by sgtpepper43** [comment]
You can use the `auth0` helper, as shown in the readme
```javascript
  var userApiUrl = auth0.baseUrl + '/users';
```
Don't know why it's still missing on auth0's site. _Somebody's_ not paying attention to this repo.

**Comment by cristiandouce** [comment]
A fix is already in production! Thanks!
