### ISSUE TITLE
Not found: Get a Firebase Session Token

### ISSUE THREAD

**Issue by jpadilla** [auth0/rules#7]
Just as a heads up, link to https://github.com/auth0/rules/blob/master/rules/generate-firebase-token.md from README.md and https://auth0.com/how-it-works return a 404.

**Comment by secobarbital** [comment]
Here's the file before it was yanked:

https://github.com/auth0/rules/blob/b909b57c1f43501e18798a37ffc460555f322086/generate-firebase-token.md
