### ISSUE TITLE
Encapsulating code in different files that can be required by the rules

### ISSUE THREAD

**Issue by tomasperezv** [auth0/rules#74]
Hi,

I'd like to know if it there is a way for the rules to load code via requires so I can reuse, encapsulate and test the core validation functions. 

I've tried to create a structure similar to:

```
|---rules
|      |------email-domain-validation.js
|
|---core
       |------domain.js
       |------whitelist.js
```

In my approach `/rules/email-domain-validation.js` tries to load code from `/core/domain.js` via `require('../core/domain.js')` as you normally would do in a node.js project.

However, when auth0 runs the `email-domain-validation.js` rule: I can see in the logs the following error: `"description": "Cannot find module '../core/domain'",`.

I haven't put `core` under `rules` since that would be taken by auth0 as if they were rules where they aren't (my first approach was to place the `core` folder under `rules`).

Is there any way for solving this?

**Comment by AmaanC** [comment]
Sorry about never getting back to you, @tomasperezv! There isn't a way to do it that way, no. You can always use a build process yourself (such as Browserify, Webpack, Grunt, etc.) to combine your modular code into one single file that can be used as a Rule.
