### ISSUE TITLE
30 days autho-mf cookie expiration  seems incorrect

### ISSUE THREAD

**Issue by gdestuynder** [auth0/rules#75]
https://github.com/auth0/rules/blob/master/rules/duo-multifactor.md Says the MFA cookie (auth0-mf) expires after 30 days and that this cannot be changed.

In my experimentation the auth0-mf cookie is set to expire 7 days after creation and is not renewed.

i.e. the MFA cookie expires after 7 days and this cannot be changed.

**Comment by AmaanC** [comment]
> In my experimentation the auth0-mf cookie is set to expire 7 days after creation and is not renewed.

Can you reliably reproduce this? If you have `allowRememberBrowser` set to `true`, the cookie does in fact get renewed, up to a maximum of 30 days.

Its expiry is set to 7 days when you examine the cookie, however, to account for inactive sessions, in which case the cookie should never be renewed. Everytime you reauthenticate, the cookie is renewed, up to 30 days.

(The issue no longer applies to the Rule document you linked, but we do [mention the same thing in the relevant document that we link to](https://auth0.com/docs/multifactor-authentication/custom#change-the-frequency-of-authentication-requests))

@gdestuynder If you still see this issue and can reproduce the behavior, feel free to reopen an issue here or [on the docs repository for the relevant page](https://github.com/auth0/docs/blob/master/articles/multifactor-authentication/custom/custom-landing.md).

**Comment by gdestuynder** [comment]
Hah, I need 7 days to test again :)

**Comment by AmaanC** [comment]
@gdestuynder Haha, no need for that. Just make sure your MFA Rule has `allowRememberBrowser: true` and that when you login as a user, you select the `Remember browser` checkbox. If you do this, you'll observe that everytime you authenticate, your `auth0-mf` cookie on `YOUR_ACCOUNT.auth0.com` is renewed to expire in 7 days since your most recent login.

**Comment by gdestuynder** [comment]
@AmaanC this works, though it also works without `allowRememberBrowser: true` in the rule (which maybe is default then) - note i was using an auth0 private instance for testing so that might be why results were unexpected when i reported this

thx!
