### ISSUE TITLE
Error when running Custom Authorization Scopes Rule example with no modification

### ISSUE THREAD

**Issue by jdheeter** [auth0/rules#79]
ERROR: Cannot set property 'scopes' of undefined

**Comment by SteveByerly** [comment]
same here. did you figure it out?

**Comment by cjthompson** [comment]
You have to use namespacing to add attributes to the id_token.  Using the Authorization Extension rule, I had to make this change:

```
    context.idToken['https://mycompany.com'] = {
      groups: user.groups,
      roles: user.roles,
      permissions: user.permissions
    };
```

I'm still trying to figure out how the OIDC compliant documentation about adding permissions into the "scopes" part of the request is supposed to work.
