### ISSUE TITLE
Convert sms-mfa redirect rule sample into email mfa

### ISSUE THREAD

**Issue by twistedstream** [auth0/rules#83]
The [sms-mfa](https://github.com/auth0/rules/tree/master/redirect-rules/sms-mfa) redirect rule sample is now obsolete since Auth0 now offers [build-in support for SMS MFA](https://auth0.com/docs/multifactor-authentication#mfa-with-sms). However, we don't yet offer an email equivalent for MFA (send a magic link in an email as a second factor), so this sample could be changed to do that instead, since the configuration is very similar. The one nice thing about email Passwordless is that it doesn't require the setup of a Twilio account.

**Comment by joshcanhelp** [comment]
Obsolete, email MFA was released last year:
https://auth0.com/blog/no-phone-no-problem-auth0-email-mfa-is-here/
