### ISSUE TITLE
Issue with targetUserId in link-users-by-email rule

### ISSUE THREAD

**Issue by grbinho** [auth0/rules#84]
Hi,

i was playing arround with [this rule](https://github.com/auth0/rules/blob/master/rules/link-users-by-email.md) today and noticed some strange behavior. My user god all users from a specific connection assigned to his identity. This was the case with ADFS connection whose user id consists of three parts, not just two:

`provider|ConnectionName|userid`

As far as I can tell it is related to this piece of code:

``` JavaScript
 var aryTmp = targetUser.user_id.split('|');
 var provider = aryTmp[0];
 var targetUserId = aryTmp[1];
```
In the end i replaced it with a function like this:

``` JavaScript
  function getUserIdFromFullId(fullId)
  {
    var parts = fullId.split('|');
    var userId = parts[1];
    
    for(var i=2; i< parts.length; i++)
    {
      userId += '|' + parts[i];
    }
    
    return userId;
  }
```

**Comment by joshcanhelp** [comment]
Obsolete, Rule no longer exists.
