### ISSUE TITLE
Google Refresh token rule is incorrect

### ISSUE THREAD

**Issue by eugeniop** [auth0/rules#85]
https://github.com/auth0/rules/blob/master/rules/google-refresh-token.md

is wrong. `refresh_token`  is stored in the `identities` array. It can be retrieved like the `access_token`

**Comment by mtt87** [comment]
So I'm following the guide and trying to get a refresh token but it's always undefined.

```js
this.lock = new Auth0Lock('q3Wx5d1EKnfLioa9zT8U8pSfOiOONFZR', 'lancelot.eu.auth0.com', {
        initialScreen:'login',
        allowedConnections: ['google-oauth2'],
        allowSignUp: false,
        auth: {
          redirect: false,
          responseType: "token",
          params: {
            'access_type': 'offline',
          },
        },
        autoclose: true
      });
```

I've even tried to add the parameter
```js
          params: {
            'access_type': 'offline',
            'approval_prompt': 'force',
          },
```

Which is working, as I get a popup asking to approve again with offline access, but still the `refreshToken` is always `undefined`.

Anyone had this kind of problem?
Using `http://cdn.auth0.com/js/lock/10.7.2/lock.min.js`

**Comment by eugeniop** [comment]
https://stackoverflow.com/questions/41133066/auth0-lock-google-oauth2-unable-to-get-refresh-token/41134698#41134698

**Comment by DzmitryU** [comment]
Hello, everyone!
I'm trying to use auth0-swift for Google login and getting google refresh_token and google_access token:

```swift
func signInWithGoogle(completion: AuthCompletionBlock?) {
        Auth0
            .webAuth()
            .connection("google-oauth2")
            .scope("offline_access")
            .start { result in
                switch result {
                case .success(let credentials):
                    if let accessToken = credentials.accessToken {
                        completion?(accessToken, nil)
                    }
                case .failure(let error):
                    print(error)
                    completion?(nil, error.localizedDescription)
                }
        }
    }
```

When I making get request from @eugeniop link, I see only "user_id", "provider", "isSocial", access_token" and "expires_in". 
http://prntscr.com/fdswns
How may I get google refresh_token to use it on server side for google access_token regeneration?
Thanks.

**Comment by mtt87** [comment]
@DzmitryU I'm not a Swift expert but seems like you are trying to obtain a Google `refresh_token` from the "client" (in your case an iOS or Mac app I guess).

You need to use the `Management API` to retrieve that token. 
https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id

Remember that `Management API` is different than `Authentication API`.

You'll need a token for your `Management API` with permission `read:user` and `read:user_idp_tokens`

That means that to make things secure you should probably have a server handling this and not put the `Management API` token inside your app.

**Comment by DzmitryU** [comment]
@mtt87 I am using token from Auth0 Management API -> API Explorer and it has all possible permissions.
Without using this token it was impossible to get even Google access_token from identities.
No, I was trying to get a Google refresh_token both from server side (node request) and web browser (https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id).

**Comment by mtt87** [comment]
I think I've spotted the problem it's not `scope: offline_access` but it's an additional parameter `access_type: offline`

This is an example of what I'm doing, I hope it helps.

1) The user has to signup using your webapp and you are asking for offline access so make sure the user see the permission to allow offline access. 
This is an example config for `lock` that I use on my webapp
```js
this.lock = new Auth0Lock('xxxxxx', 'xxx.eu.auth0.com', {
        initialScreen:'login',
        allowedConnections: ['google-oauth2'],
        allowSignUp: false,
        auth: {
          redirect: false,
          responseType: "token",
          approval_prompt: 'force',
          params: {
            'access_type': 'offline',
            'approval_prompt' : 'force'
          },
        },
        autoclose: true
      });
```

2) Right after the user signed up you are able from the server to make the request to retrieve the google refresh_token. As far as I understood, you can do this only the first time and then you won't be able to retrieve the token anymore.
What I do is make a `POST /users` to create the new user with `{ userId: xxx, userEmail: yyy }`, then the server is making a request using `management API` to retrieve the user. See that there is no scope or stuff like that, it's just a plain call.

```js
app.post('/users', jwtCheck, (req, res) => {
  const { userId, userEmail } = req.body;
  auth0Management.users.get({
    id: userId,
  }).then((user) => {
    // retrieve Google refresh_token from Auth0 and save it for future use
    if (user.identities[0].refresh_token !== undefined) {
      const { refresh_token, access_token } = user.identities[0];
    // do something with your token
```

**Comment by DzmitryU** [comment]
@mtt87 You where totally right. _scope: offline_access_ and _access_type: offline_ are different options.
Finally I've just added to my request following line:

` .parameters(["access_type" : "offline", "approval_prompt" : "force"]) // parameters to obtain google refresh token`

It helped and now after log in user.identities contains google refresh token.
Thanks a lot! You helped me to solve issue, I was working with for long time.
